extends Node
class_name _Enum_ALecandria


var ENUMS_TO_STRING = {
	 "BASE_GAME_DATA_PATH" : BASE_GAME_DATA_PATH
	,"STABLE_GAME_DATA"    : STABLE_GAME_DATA
	,"COMMUNITY_GAME_DATA" : COMMUNITY_GAME_DATA
	,"PERSONAL_GAME_DATA"  : PERSONAL_GAME_DATA
}



const BASE_GAME_DATA_PATH = "res://GameData/GameElements/"

const COMMUNITY_GAME_DATA = BASE_GAME_DATA_PATH+"/Community"
const PERSONAL_GAME_DATA  = BASE_GAME_DATA_PATH+"/Personal"
const STABLE_GAME_DATA    = BASE_GAME_DATA_PATH+"/Stable"


