extends Node
class_name _Enum_Player


var ENUMS_TO_STRING = {
	 "ROOMS_FOR_TRAIT_NEEDED" : ROOMS_FOR_TRAIT_NEEDED
	,"MAX_TEAM_SIZE"          : MAX_TEAM_SIZE
	,"ATTRIBUTE"              : ATTRIBUTE
	,"SKILL"                  : SKILL
}


const ROOMS_FOR_TRAIT_NEEDED = 3
const MAX_TEAM_SIZE          = 4




enum SKILL {
	# MEAT			 # MAGIC                 # MATRIX
	CRAFTING     ,   PHYLOSOPHIZING      ,   CONCEPTUALICING        # IMPOVICING
	PERCEVING    ,   ASSENSING           ,   DEBUGGING				# FINDING SOMETHING HIDDEN
	ENDURING     ,   COPING              ,   FILTERING				# GOING THROUGH TOUGH TERRAIN
	SNEAKING     ,   REPRESSING          ,   SILENCING              # STAYING HIDDEN
}



enum ATTRIBUTE{
	AGILLITY
	CONSTITUTION
	STRENGTH
	REACTION

	LOGIC
	INTUITION
	WILLPOWER
	CHARISMA
}


