extends Node
class_name _Enum_SokraTILES


var ENUMS_TO_STRING = {
	 "MOUSE_INPUT_MODE" : MOUSE_INPUT_MODE
	,"TILE_PIXEL_SIZE"  : TILE_PIXEL_SIZE
	,"CENTER_TO_DRAW"   : CENTER_TO_DRAW
	,"DIRECTION_FOUR"   : DIRECTION_FOUR
	,"ACTION_PHASE"     : ACTION_PHASE
	,"TYPES_ON_MAP"     : TYPES_ON_MAP
	,"M_TYPE"           : M_TYPE
	,"LAYER"            : LAYER
}



enum TYPES_ON_MAP { TILE   , ACTOR  , INTERACT       # CORE
					MARKER , PLAYER , LOOT_SOURCE }  # MISC
enum ACTION_PHASE {  EFFECT_DONE , PLAYER_DONE , NPC_DONE  }



const CENTER_TO_DRAW  = Vector2(32,31)
const TILE_PIXEL_SIZE = 16



enum MOUSE_INPUT_MODE{  ONLOOK , LOOT  }
enum M_TYPE {  MEAT , MAGIC , MATRIX  }
enum DIRECTION_FOUR {  NORTH , EAST , SOUTH , WEST  }



# REFACTOR set static int 
enum LAYER {
	ACTOR
	PLAYER
	MEAT_GROUND 
	MEAT_INTERACTABLE
	MATRIX_GROUND
	MATRIX_INTERACTABLE
	MAGIC_GROUND
	MAGIC_INTERACTABLE	
	SELECTION
	CONDITION
}

enum SELECTABLE_LAYER{
	ACTOR
	MEAT_GROUND 
	MEAT_INTERACTABLE
}


