extends Node





var EVENT = {
	"LIST_PERFORMANCE" : EVENT_SYNTAX.LIST_PERFORMANCE(),
	"MATH_OPERATORS" : EVENT_SYNTAX.MATH_OPERATOR(),
	"STAT_MODS" : STAT_MOD_INDEX.getIndex(),
	"FILLER" : EVENT_SYNTAX.FILLER(),
	"SYNONYMS" : EVENT_SYNTAX.SYNONYMS(),
	"CONCEPTS" : EVENT_SYNTAX.ALL_CONCEPTS(),
	"CONNECTORS" : EVENT_SYNTAX.CONNECTOR(),
	"EFFECTS" : EFFECTS_INDEX.getIndex()
}





